apiVersion: iam.services.k8s.aws/v1alpha1
kind: Policy
metadata:
  name: {{ include "spark-tenant.fullname" . }}
  labels:
    {{- include "spark-tenant.labels" . | nindent 4 }}
spec:
  name: {{ include "spark-tenant.fullname" . }}
  description: IAM Policy for Spark Tenant Service Account
  #This example Policy allows to list all S3 Buckets
  policyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:ListAllMyBuckets","Resource":"arn:aws:s3:::*"},{"Effect":"Allow","Action":["s3:List*"],"Resource":["*"]}]}'