apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ include "spark-tenant.fullname" . }}
  labels:
    {{- include "spark-tenant.labels" . | nindent 4 }}
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: {{ .Values.nodePool.instanceFamily }}
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: {{ .Values.nodePool.instanceSize }}
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ include "spark-tenant.fullname" . }}
      expireAfter: 720h # 30 * 24h = 720h
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{ include "spark-tenant.fullname" . }}
spec:
  amiFamily: AL2023 # Amazon Linux 2023  
  role: {{ .Values.nodePool.karpenterRole }}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.cluster.name }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.cluster.name }}
  amiSelectorTerms:
    - alias: al2023@latest